apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mics-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mics-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: hello-world
        image: mics233.azurecr.io/hello-world:3
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mics-test
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: mics-test
