apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{image_name}}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
  - hosts: 
    - {{host_name}}
    secretName: {{host_name}}
  rules:
  - host: {{host_name}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{image_name}}
          servicePort: 80
      - path: /wp-admin
        backend:
          serviceName: {{image_name}}
          servicePort: 80